const AfricaMapAllocations = {
  EG: 'Ägypten',
  SD: 'Anglo-Ägyptischer Sudan',
  SS: 'Anglo-Ägyptischer Sudan',
  UG: 'Uganda (Britisches Protektorat)',
  KE: 'Kenia (Britisches Protektorat)',
  ET: 'Äthiopien',
  ER: 'Eritrea (Italienische Kolonie)',
  SO: 'Italienisch-Somaliland',
  DJ: 'Französisch-Somaliland',
  TZ: 'Deutsch-Ostafrika',
  RW: 'Deutsch-Ostafrika',
  BI: 'Deutsch-Ostafrika',
  MZ: 'Portugiesisch-Ostafrika',
  MW: 'Nyassaland (Britisches Protektorat)',
  ZM: 'Nordrhodesien (Britisches Protektorat)',
  ZW: 'Südrhodesien (Britisches Protektorat)',
  NA: 'Deutsch-Südwestafrika',
  ZA: 'Südafrika (Britische Kolonie)',
  BW: 'Bechuanaland (Britisches Protektorat)',
  LS: 'Basutoland (Britisches Protektorat)',
  SZ: 'Swasiland (Britisches Protektorat)',
  AO: 'Angola (Portugiesische Kolonie)',
  CD: 'Belgisch-Kongo',
  CG: 'Französisch-Kongo',
  GA: 'Französisch-Äquatorialafrika',
  GQ: 'Spanisch-Guinea',
  ST: 'São Tomé und Príncipe (Portugiesische Kolonie)',
  CM: 'Kamerun (Deutsche Kolonie)',
  TD: 'Französisch-Äquatorialafrika',
  NE: 'Französisch-Westafrika',
  BJ: 'Französisch-Westafrika',
  NG: 'Nigeria (Britische Kolonie)',
  GH: 'Goldküste (Britische Kolonie)',
  TG: 'Togo (Deutsche Kolonie)',
  CI: 'Elfenbeinküste (Französisch-Westafrika)',
  BF: 'Französisch-Westafrika',
  ML: 'Französisch-Westafrika',
  MR: 'Französisch-Westafrika',
  SN: 'Französisch-Westafrika',
  GM: 'Gambia (Britisches Protektorat)',
  SL: 'Sierra Leone (Britische Kolonie)',
  LR: 'Liberia',
  GN: 'Französisch-Westafrika',
  CV: 'Kap Verde (Portugiesische Kolonie)',
  DZ: 'Algerien (Französische Kolonie)',
  LY: 'Libyen (Italienische Kolonie)',
  MA: 'Marokko (Französisches Protektorat, nördliche Zone spanisch)',
  EH: 'Spanisch-Westafrika',
  TN: 'Tunesien (Französisches Protektorat)',
};

export default AfricaMapAllocations;
